-- 시퀀스 생성
CREATE SEQUENCE META_SEQ
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 99999
  MINVALUE 1
  NOCYCLE;

-- 시퀀스 삭제
DROP SEQUENCE META_SEQ;

-- 시퀀스 수정
ALTER SEQUENCE META_SEQ
  MAXVALUE 1000;


-- 시퀀스 검색(현재 계정의 모든 시퀀스를 보여줌)
SELECT SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG 
FROM USER_SEQUENCES;
