/* 현재 캐릭터셋 확인 */
select
 distinct(nls_charset_name(charsetid)) CHARACTERSET,
 decode(type#, 1, decode(charsetform, 1, 'VARCHAR2', 2, 'NVARCHAR2','UNKOWN'),
 9, decode(charsetform, 1, 'VARCHAR', 2, 'NCHAR VARYING', 'UNKOWN'),
 96, decode(charsetform, 1, 'CHAR', 2, 'NCHAR', 'UNKOWN'),
 112, decode(charsetform, 1, 'CLOB', 2, 'NCLOB', 'UNKOWN')) TYPES_USED_IN
from sys.col$
where charsetform in (1,2) and type# in (1, 9, 96, 112)
ORDER BY characterset;



/* 캐릭터셋 통일 */
sqlplus 실행 (sqlplus 에서 해야지 되고 다른데서 안되네.)
아래 명령어 붙여넣고 실행

SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER SYSTEM ENABLE RESTRICTED SESSION;
ALTER SYSTEM SET JOB_QUEUE_PROCESSES=0;
ALTER SYSTEM SET AQ_TM_PROCESSES=0;
ALTER DATABASE OPEN;
COL VALUE NEW_VALUE CHARSET
SELECT VALUE 
FROM NLS_DATABASE_PARAMETERS 
WHERE PARAMETER='NLS_CHARACTERSET';

COL VALUE NEW_VALUE NCHARSET
SELECT VALUE 
FROM NLS_DATABASE_PARAMETERS 
WHERE PARAMETER='NLS_NCHAR_CHARACTERSET';

ALTER DATABASE CHARACTER SET INTERNAL_USE &CHARSET;

ALTER DATABASE NATIONAL CHARACTER SET INTERNAL_USE &NCHARSET;

-- oracle reboot 2번
SHUTDOWN IMMEDIATE;
STARTUP;
SHUTDOWN IMMEDIATE;
STARTUP;