USE movieproject;

CREATE TABLE `grade` (
  `NAME` varchar(20) DEFAULT NULL,
  `DEGREE` int DEFAULT NULL,
  `POINT` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;


CREATE TABLE `student` (
  `NAME` varchar(20) NOT NULL,
  `AGE` int DEFAULT NULL,
  `GENDER` varchar(1) DEFAULT NULL,
  `ADDRESS` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;


INSERT INTO STUDENT VALUES(강경모,	20,	남);
INSERT INTO STUDENT VALUES(김광호,	34,	남);
INSERT INTO STUDENT VALUES(김명진,	39,	여);
INSERT INTO STUDENT VALUES(김범수,	31,	남);	
INSERT INTO STUDENT VALUES(김용범,	42,	남);	
INSERT INTO STUDENT VALUES(김종성,	16,	여);	
INSERT INTO STUDENT VALUES(김지혜,	35,	남);	
INSERT INTO STUDENT VALUES(김채영,	76,	남);	
INSERT INTO STUDENT VALUES(남한얼,	34,	여);	
INSERT INTO STUDENT VALUES(노현호,	63,	남);	
INSERT INTO STUDENT VALUES(모원기,	23,	남);	
INSERT INTO STUDENT VALUES(문종수,	21,	여);	
INSERT INTO STUDENT VALUES(박현정,	23,	남);	
INSERT INTO STUDENT VALUES(손대영,	37,	남);	
INSERT INTO STUDENT VALUES(손아람,	17,	여);	
INSERT INTO STUDENT VALUES(엄준식,	26,	남);	
INSERT INTO STUDENT VALUES(윤영민,	27,	남);	
INSERT INTO STUDENT VALUES(윤형준,	28,	여);	
INSERT INTO STUDENT VALUES(이승현,	35,	남);	
INSERT INTO STUDENT VALUES(이찬희,	34,	남);	
INSERT INTO STUDENT VALUES(장원혁,	33,	여);	
INSERT INTO STUDENT VALUES(조종학,	33,	남);	
INSERT INTO STUDENT VALUES(최하늘,	23,	남);	
INSERT INTO STUDENT VALUES(추홍재,	35,	여);	
INSERT INTO STUDENT VALUES(한민우,	27,	남);


			

INSERT INTO GRADE VALUES ('강경모', 1, 30);
INSERT INTO GRADE VALUES ('김광호', 1, 60);
INSERT INTO GRADE VALUES ('김명진', 1, 80);
INSERT INTO GRADE VALUES ('김범수', 1, 84);
INSERT INTO GRADE VALUES ('김용범', 1, 84);
INSERT INTO GRADE VALUES ('김지혜', 1, 30);
INSERT INTO GRADE VALUES ('김채영', 1, 30);
INSERT INTO GRADE VALUES ('노현호', 1, 30);
INSERT INTO GRADE VALUES ('모원기', 1, 30);
INSERT INTO GRADE VALUES ('문종수', 1, 30);
INSERT INTO GRADE VALUES ('박현정', 1, 30);
INSERT INTO GRADE VALUES ('홍길동', 1, 30);
INSERT INTO GRADE VALUES ('아이유', 1, 30);

SELECT * FROM GRADE;
SELECT * FROM STUDENT;
SELECT COUNT(*) FROM GRADE;		#13
SELECT COUNT(*) FROM STUDENT;	#25
DESC GRADE;
DESC STUDENT;

# LEFT JOIN 25.  11명 점수있음
# RIGHT JOIN 13. 13명 모두 점수있음
# INNER JOIN 11. 모두 정보보임.
;
SELECT G.DEGREE, S.NAME, G.POINT, S.AGE, S.GENDER
FROM STUDENT S INNER JOIN GRADE G
ON G.NAME = S.NAME
;
